config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "posts#index"
  get "users/:id/likes" => "users#likes"
  resources :users, only: [:show, :edit, :update]
  resources :posts, only: [:new, :create, :show, :destroy] do
    resources :comments, only: :create
    resources :likes, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :text, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :post
  belongs_to :user

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_taggable
  default_scope -> { order(created_at: :desc) }
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :likes, dependent: :destroy

  validates :image, presence: true

  mount_uploader :image, ImageUploader
  # def like_by?(user) #ユーザーがいいねをしてあるかどうかを確認するための記述。いいねボタンを追記するmy_books/showページで後々使う。
  #   likes.where(user_id: user.id).exists?
  # end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  
  validates :name, presence: true, uniqueness: true
  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/posts/#{comment.post.id}"
  end
  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.includes(:user).page(params[:page]).per(10)
    @tags = ActsAsTaggableOn::Tag.most_used
    if params[:tag_name]
      @posts = Post.tagged_with("#{params[:tag_name]}").page(params[:page]).per(10)
    end
    @like = Like.new
  end
  def new
    @post = Post.new
  end
  def create
    
    Post.create(post_params)
    redirect_to root_path
  end
  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
    @like = Like.new
    @likes_count = Like.where(post_id: @post.id).count
  end
  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_path
  end
  private
  def post_params
    params.require(:post).permit(:image, :content, :tag_list).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(5)
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def likes
    @user = User.find_by(id: params[:id])
    @likes = Like.where(user_id: @user.id)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.haml
%footer.footer-fixed
  .footer-bk
    .footer
      Copyright PicTag 2020.

app/views/layouts/_header.html.haml
%header.header-fixed
  .header-bk
    .header
      = link_to root_path do
        %h1
          PicTag

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title PicTag
    -# = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    %link{:href => "https://fonts.googleapis.com/css?family=Baloo+Thambi+2|Kosugi+Maru|Oleo+Script&display=swap", :rel => "stylesheet"}/
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"}
    -# = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    .wrapper
      = render "layouts/header"
      = yield
      = render "layouts/footer"

app/views/likes/_like.html.haml
- if user_signed_in?
  - if current_user.already_liked?(post)
    = link_to post_like_path(post.id, post.user_id), method: :delete do
      .unlike
        %i.fas.fa-heart
  - else
    = link_to post_likes_path(post.id), method: :post do
      %i.fas.fa-heart
- else
  %i.fas.fa-heart
%p.likes-count
  - if post.likes.count > 0
    = post.likes.count

app/views/likes/create.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/likes/destroy.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/posts/_main.html.haml
.main
  %ul.main__header
    %li.main__header__item.active
      %i.fas.fa-envelope-open-text
      NEW POSTS
    %li.main__header__item
      %i.fas.fa-crown
      TAG RANKING
  %ul.list.show
    - @posts.each do |post|
      %li.post
        .upper-info
          = link_to user_path(post.user) do
            %p.upper-info__talker
              = post.user.name
              &nbsp;
          %p.upper-info__date
            = post.created_at.strftime("%Y/%m/%d %H:%M")
        .middle-content
          = image_tag post.image.url, class: 'middle-content__picture'
          .middle-content__lower
            %p.text
              = post.content
            .icon-box
              = link_to post_path(post.id) do
                .icon-box__comment
                  %i.fas.fa-comment
                  %p.comment-count
                    - if post.comments.count > 0
                      = post.comments.count
              .icon-box__heart#likes_buttons_
                = render partial: 'likes/like', locals: { post: post }
        .lower-tag
          %ul.tag-list
            - post.tags.each do |tag|
              %li.tag
                .tag__name
                  = link_to tag, root_path(tag_name: tag.name), class: "text-white"
    = paginate(@posts)
  %ul.list
    - @tags.each.with_index(1) do |tag, i|
      %li.mtag-list
        .rank
          = i
          &period;
        .mtag
          .mtag__name
            = link_to tag, root_path(tag_name: tag.name)

app/views/posts/_side_bar.html.haml
.side-bar
  - if user_signed_in?
    %p.user-name
      %i.fas.fa-user
      = current_user.name
    %ul.user-menu
      = link_to new_post_path do
        %li.create-post
          %i.fas.fa-edit
          CREATE A POST
      = link_to user_path(current_user) do
        %li.my-post
          %i.fas.fa-inbox
          MY POSTS
      = link_to "/users/#{current_user.id}/likes" do
        %li.my-like
          %i.fas.fa-heart
          MY LIKES
      = link_to edit_user_path(current_user) do
        %li.edit-account
          %i.fas.fa-user-edit
          EDIT ACCOUNT
      = link_to destroy_user_session_path,method: :delete do
        %li.log-out
          %i.fas.fa-sign-out-alt
          LOG OUT
  - else
    %p.user-name
      %i.fas.fa-user
      GUEST
    %ul.user-menu
      = link_to new_user_session_path do
        %li.log-in
          %i.fas.fa-sign-in-alt
          LOG IN
      = link_to new_user_registration_path do
        %li.create-account
          %i.fas.fa-user-plus
          CREATE ACCOUNT

app/views/posts/index.html.haml
.container
  = render "side_bar"
  = render "main"

app/views/posts/new.html.haml
.container
  = render "side_bar"
  .main
    .pc-frame
      .pc-frame__in
        .create-a-post
          %h2
            CREATE A POST
          = form_for @post, html: { class: "form"} do |form|
            .field.image
              = form.label 'サムネイル（スクリーンショットなど）' do
                #img_field{:onclick => "$('#file').click()"}
                  - if @post.image.url.present?
                    = image_tag(@post.image.url)
                  - else
                    %i.fas.fa-image
                    %i.fas.fa-file-upload.add
              = form.file_field :image, class: "image", style: "display:none;", id: "file"
            = form.text_area :content, placeholder: "TEXT", maxlength: "50", class: "form__text"
            = form.text_field :tag_list, value: @post.tag_list.join(','), placeholder: "tags  (e.g.: dog,cat,please like)", class: "form__tags"
            .button-box
              = form.submit 'SUBMIT!', class: "button-box__btn"

app/views/posts/show.html.haml
.container
  = render "side_bar"
  .main
    .post-list2
      .post
        .upper-info
          = link_to "#" do
            %p.upper-info__talker
              = @post.user.name
              &nbsp;
          - if user_signed_in? && current_user.id == @post.user_id
            %p.upper-info__date1
              = @post.created_at.strftime("%Y/%m/%d %H:%M")
            = link_to post_path(@post.id), method: :delete, class: "upper-info__delete" do
              %i.fas.fa-trash-alt
          - else
            %p.upper-info__date
              = @post.created_at.strftime("%Y/%m/%d %H:%M")
        .middle-content
          = image_tag @post.image.url, class: 'middle-content__picture'
          .middle-content__lower
            %p.text
              = @post.content
            .icon-box
              .icon-box__heart
                - if user_signed_in?
                  - if current_user.already_liked?(@post)
                    = link_to post_like_path(@post), method: :delete do
                      .unlike
                        %i.fas.fa-heart
                  - else
                    = link_to post_likes_path(@post), method: :post do
                      %i.fas.fa-heart
                - else
                  %i.fas.fa-heart
                %p.likes-count
                  - if @likes_count > 0
                    = @likes_count
        .lower-tag
          %ul.tag-list
            - @post.tags.each do |tag|
              %li.tag
                .tag__name
                  = link_to tag, root_path(tag_name: tag.name), class: "text-white"
      .alert - COMMENTS -
      - if @comments
        - @comments.each do |comment|
          .comment
            .upper-info
              = link_to "/users/#{comment.user_id}" do
                %p.upper-info__talker
                  = comment.user.name
              %p.upper-info__date
                = comment.created_at.strftime("%Y/%m/%d %H:%M")
            .comment-content
              .comment-content__lower
                %p.text
                  = comment.text
      .comment-form
        - if current_user
          = form_for [@post, @comment] do |form|
            = form.text_area :text, placeholder: "MAKE A COMMENT", rows: "3", class: "form__comment"
            .button-box
              = form.submit "SEND", class: "button-box__btn"
        - else
          %strong
            .alert
              %p ※※※ You need to login to comment!! ※※※

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 EDIT ACCOUNT
      %h5 アカウントの編集
      = link_to "LOG OUT", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "TOP", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'

app/views/users/likes.html.haml
-# - @likes.each do |like|
-#   - post = Post.find_by(id: like.post_id)
-#   - user = User.find_by(id: post.user_id)
-#   = link_to( user.name, "/users/#{user.id}" )
-#   = link_to(post.content, "/posts/#{post.id}")

.container
  = render "posts/side_bar"
  .main
    .main__header1
      = @user.name
      's LIKES
    %ul.post-list1
      - @likes.each do |like|
        - post = Post.find_by(id: like.post_id)
        %li.post
          .upper-info
            = link_to "#" do
              %p.upper-info__talker
                = post.user.name
                &nbsp;
              %p.upper-info__date
                = post.created_at.strftime("%Y/%m/%d %H:%M")
          .middle-content
            = image_tag post.image.url, class: 'middle-content__picture'
            .middle-content__lower
              %p.text
                = post.content
              .icon-box
                = link_to post_path(post.id) do
                  .icon-box__comment
                    %i.fas.fa-comment
                    %p.comment-count
                      - if post.comments.count > 0
                        = post.comments.count
                .icon-box__heart
                  - if current_user.already_liked?(post)
                    = link_to post_like_path(post.id, post.user_id), method: :delete do
                      .unlike
                        %i.fas.fa-heart
                  %p.likes-count
                    = post.likes.count
          .lower-tag
            %ul.tag-list
              - post.tags.each do |tag|
                %li.tag
                  .tag__name
                    = link_to tag, root_path(tag_name: tag.name), class: "text-white"

app/views/users/show.html.haml
.container
  = render "posts/side_bar"
  .main
    .main__header1
      = @user.name
      's POSTS
    %ul.post-list1
      - @posts.each do |post|
        %li.post
          .upper-info
            %p.upper-info__talker
              = post.user.name
              &nbsp;
            - if user_signed_in? && current_user.id == post.user_id
              %p.upper-info__date1
                = post.created_at.strftime("%Y/%m/%d %H:%M")
              = link_to post_path(post.id), method: :delete, class: "upper-info__delete", id: "delete-btn" do
                %i.fas.fa-trash-alt
            - else
              %p.upper-info__date
                = post.created_at.strftime("%Y/%m/%d %H:%M")
          .middle-content
            = image_tag post.image.url, class: 'middle-content__picture'
            .middle-content__lower
              %p.text
                = post.content
              .icon-box
                = link_to post_path(post.id) do
                  .icon-box__comment
                    %i.fas.fa-comment
                    %p.comment-count
                      - if post.comments.count > 0
                        = post.comments.count
                .icon-box__heart
                  = render partial: 'likes/like', locals: { post: post }
          .lower-tag
            %ul.tag-list
              - post.tags.each do |tag|
                %li.tag
                  .tag__name
                    = link_to tag, root_path(tag_name: tag.name), class: "text-white"
      = paginate(@posts) 